[[edge_functions]]
  path = "/"
  function = "referer"

[context.dev.environment]
  HTTP_REFERER_CHECK = "http://localhost:8888/"

[template.environment]
  HTTP_REFERER_CHECK = "HTTP_REFERER_CHECK env var"